export const SHOP_ACTIONS = {
  SET_SHOP_DB: 'SHOP/SET_SHOP_DB',
  TOGGLE_SHOW_SPICINESS: 'SHOP/TOGGLE_SHOW_SPICINESS',
  SET_IS_LOADED: 'SHOP/SET_IS_LOADED',
  SET_IS_LOADING: 'SHOP/SET_IS_LOADING'
};