export const SHOP_ACTIONS = {
  FETCH_DATABASE_ASYNC: 'shop/FETCH_DATABASE_ASYNC',
  FETCH_DATABASE_START: 'shop/FETCH_DATABASE_START',
  FETCH_DATABASE_SUCCESS: 'shop/FETCH_DATABASE_SUCCESS',
  FETCH_DATABASE_FAILED: 'shop/FETCH_DATABASE_FAILED',
  TOGGLE_SHOW_SPICINESS: 'shop/TOGGLE_SHOW_SPICINESS'
};