export const SHOP_ACTIONS = {
  SET_SHOP_DB: 'shop/SET_SHOP_DB',
  TOGGLE_SHOW_SPICINESS: 'shop/TOGGLE_SHOW_SPICINESS',
  SET_IS_LOADED: 'shop/SET_IS_LOADED',
  SET_IS_LOADING: 'shop/SET_IS_LOADING'
};